' Create_emPolygonizer4_PolymeshPlugin
' Initial code generated by XSI SDK Wizard
' Executed Tue Jun 23 22:05:04 UTC+0200 2009 by Administrator
' 
' Tip: To add a command to this plug-in, right-click in the 
' script editor and choose Tools > Add Command.
' 
' Tip: To get help on a callback, highlight the callback name
' (for example, "Init", "Define", or "Execute") and press F1.

function XSILoadPlugin( in_reg )
	in_reg.Author = "Eric Mootz"
	in_reg.Name = "Create_emPolygonizer4_PolymeshPlugin"
	in_reg.Email = "info@mootzoid.com"
	in_reg.URL = "http://www.mootzoid.com/"
	in_reg.Major = 1
	in_reg.Minor = 0

	in_reg.RegisterCommand "Create_emPolygonizer4_Polymesh","Create_emPolygonizer4_Polymesh"
	in_reg.RegisterMenu siMenuTbModelCreatePolygonMeshID,"Create_emPolygonizer4_Polymesh_Menu",false,false
	'RegistrationInsertionPoint - do not remove this line

	XSILoadPlugin = true
end function

function XSIUnloadPlugin( in_reg )
	dim strPluginName
	strPluginName = in_reg.Name
	'Application.LogMessage strPluginName & " has been unloaded.",siVerbose
	XSIUnloadPlugin = true
end function

function Create_emPolygonizer4_Polymesh_Init( in_ctxt )
	dim oCmd
	set oCmd = in_ctxt.Source
	oCmd.Description = ""
	oCmd.ReturnValue = true

	Create_emPolygonizer4_Polymesh_Init = true
end function

function Create_emPolygonizer4_Polymesh_Execute(  )

	' Get current selection list
	set selList = GetValue("SelectionList")

	' create an empty polygon mesh
	SIGetPrim "EmptyPolygonMesh", "emPolygonizer4", , , obj

	' create new selection based on selList
	DeselectAll
	sel = obj.fullname
	for each o in selList
		sel = sel & "," & o.fullname
	next
	SelectObj sel

	' apply the emPolygonizer4 operator
	Apply_emPolygonizer4

	' select freshly created mesh
	DeselectAll
	SelectObj obj.fullname

	' create the ICE Tree for the user data
	ApplyOp "ICETree", , siNode, , , siConstructionModeSecondaryShape
	AddICECompoundNode "emP4 _ ICE Data Generator", obj.fullname & ".polymsh.ICETree"
	ConnectICENodes obj.fullname & ".polymsh.ICETree.port1", obj.fullname & ".polymsh.ICETree.emP4___ICE_Data_Generator.Execute"

	' select freshly created mesh
	DeselectAll
	SelectObj obj.fullname

	' 
	Create_emPolygonizer4_Polymesh_Execute = true
end function

function Create_emPolygonizer4_Polymesh_Menu_Init( in_ctxt )
	dim oMenu
	set oMenu = in_ctxt.Source
	oMenu.AddCommandItem "emPolygonizer4","Create_emPolygonizer4_Polymesh"
	Create_emPolygonizer4_Polymesh_Menu_Init = true
end function

