' emPolygonizer4_FileSelectBoxPlugin
' Initial code generated by Softimage SDK Wizard
' Executed Thu Apr 28 10:13:32 UTC+0200 2011 by Administrator
' 
' Tip: To add a command to this plug-in, right-click in the 
' script editor and choose Tools > Add Command.

function XSILoadPlugin( in_reg )
	in_reg.Author = "Eric Mootz"
	in_reg.Name = "emPolygonizer4_FileSelectBoxPlugin"
	in_reg.Major = 1
	in_reg.Minor = 0

	in_reg.RegisterCommand "emPolygonizer4_FileSelectBox","emPolygonizer4_FileSelectBox"
	'RegistrationInsertionPoint - do not remove this line

	XSILoadPlugin = true
end function

function XSIUnloadPlugin( in_reg )
	dim strPluginName
	strPluginName = in_reg.Name
	Application.LogMessage strPluginName & " has been unloaded.",siVerbose
	XSIUnloadPlugin = true
end function

function emPolygonizer4_FileSelectBox_Init( in_ctxt )
	dim oCmd
	set oCmd = in_ctxt.Source
	oCmd.Description = ""
	oCmd.SetFlag siNoLogging,true
	oCmd.ReturnValue = true

	dim oArgs
	set oArgs = oCmd.Arguments
	oArgs.Add "DialogTitle",	siArgumentInput,	"Select File"
	oArgs.Add "InitialDir",		siArgumentInput,	"."
	oArgs.Add "FileBaseName",	siArgumentInput,	"untitled"
	oArgs.Add "Filter",			siArgumentInput,	"emPolygonizer (*.emp2)|*.emp2|All Files (*.*)|*.*||"
	oArgs.Add "mode",			siArgumentInput,	"open"
	emPolygonizer4_FileSelectBox_Init = true
end function

'
' file select dialogue for emPolygonizer4
'	params:	DialogTitle		title of the dialogue.
'			InitialDir		initial directory.
'			FileBaseName	file base name.
'			Filter			filter (see XSI SDK doc).
'			mode			"save" for a save file dialogue, else an open dialogue.
'	return value:	an empty string if the user pressed cancel, else a string that looks like this:
'					"FilePathName|*|FileName|*|FileBaseName|*|FileExtension|*|FilePath"
'
function emPolygonizer4_FileSelectBox_Execute( DialogTitle,InitialDir,FileBaseName,Filter,mode )
	' init return value
	emPolygonizer4_FileSelectBox_Execute = ""

	' init browser and display it
	dim oFileBrowser
	set oFileBrowser = XSIUIToolkit.FileBrowser
	oFileBrowser.DialogTitle		= DialogTitle
	oFileBrowser.InitialDirectory	= InitialDir
	oFileBrowser.FileBaseName		= FileBaseName
	oFileBrowser.Filter				= Filter
	if mode = "save" then
		oFileBrowser.ShowSave
	else
		oFileBrowser.ShowOpen
	end if

	' if user did not press cancel then put the result in the return value
	if oFileBrowser.FilePathName <> "" then
		emPolygonizer4_FileSelectBox_Execute = emPolygonizer4_FileSelectBox_Execute & oFileBrowser.FilePathName		& "|*|"
		emPolygonizer4_FileSelectBox_Execute = emPolygonizer4_FileSelectBox_Execute & oFileBrowser.FileName			& "|*|"
		emPolygonizer4_FileSelectBox_Execute = emPolygonizer4_FileSelectBox_Execute & oFileBrowser.FileBaseName		& "|*|"
		emPolygonizer4_FileSelectBox_Execute = emPolygonizer4_FileSelectBox_Execute & oFileBrowser.FileExtension	& "|*|"
		emPolygonizer4_FileSelectBox_Execute = emPolygonizer4_FileSelectBox_Execute & oFileBrowser.FilePath
	end if

	' we're done
end function

